# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: n3wl1fe
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: meet-auth-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Meet

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    AUTH_URI: ${file(config.json):AUTH_URI}
    TOKEN_URI: ${file(config.json):TOKEN_URI}
    AUTH_PROVIDER_CERT_URL: ${file(config.json):AUTH_PROVIDER_CERT_URL}
    REDIRECT_URI: ${file(config.json):REDIRECT_URI}
    JAVASCRIPT_ORIGIN: ${file(config.json):JAVASCRIPT_ORIGIN}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true
  getCalenderEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true
